### PR TITLE
Added regex to ignore html/xml tags in query

### PR DESCRIPTION
**Pull request by devExcale**
Hi,

I like to colour my notes based on the vocab's pitch accent, so I have html tags inside the vocab's field.

I added a regex to strip away any xml tag from the input field before querying the dict, this way only the vocab is included in the query.

Let me know,
Emanuele

### CODE REVIEW

**Comment by christopher-chandler** [comment]
Can you give me an example screenshot of how this looks in anki?

**Comment by devExcale** [comment]
Yes, absolutely.

The first screenshot is before generating the frequency, the second one is after generation.
The pre-op/post-op dialogs are the same, so I didn't screenshot them.

image

image

**Comment by christopher-chandler** [comment]
okay, that looks cool! Could you please update the README.MD to reflect this change? I'll update the anki plugin so that it'll be available there too.

**Comment by devExcale** [comment]
Sure, I'll do it straight away.

Btw, would you mind waiting for a bit before updating the plugin on anki? I'm trying another similar feature and I'll open another pull request once I'm done.

**Comment by christopher-chandler** [comment]
Okay, I'll wait for you to do your second feature. Please also add that to the readme. Once you are done  and I'll look test them and update the anki plug-in accordingly.

**Comment by devExcale** [comment]
Thank you, this is done. Is the readme alright?

**Comment by christopher-chandler** [comment]
readme looks good!

**Comment by devExcale** [comment]
You didn't close the PR and the new changes included the previous ones, so I hope you don't mind I reused this PR.

The readme should say exactly what the new feature is: in addition to xml tags, now parenthesis and leading/trailing whitespaces (including non-breaking ones) should be ignored. I changed the screenshot in the readme to reflect this.

**Comment by christopher-chandler** [comment]
I didn't close because I want to test it on my side, but using this pr is okay too. I'll close this pr today after I have tested and updated everything.

**Pull request merged**
